<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        // #1_Перепишите один из примеров раздела Цепочка промисов, используя async/await вместо .then/catch:
        function loadJson(url) {
            return fetch(url)
                .then(response => {
                    if (response.status == 200) {
                        return response.json();
                    } else {
                        throw new Error(response.status);
                    }
                })
        }
        loadJson('no-such-user.json') // (3)
            .catch(alert); // Error: 404

        // Ответ:

        async function loadJson(url) {
            let response = await fetch(url);
            if (response.status == 200) {
                let json = await response.json();
                return json;
            }
            throw new Error(response.status);
        }
        loadJson('no-such-user.json')
            .catch(alert); // Error: 404

        // №_2
        // Ниже пример из раздела Цепочка промисов, перепишите его, используя async/await 
        // вместо .then/catch.
        // В функции demoGithubUser замените рекурсию на цикл: используя async/await, сделать это будет просто.
        class HttpError extends Error {
            constructor(response) {
                super(`${response.status} for ${response.url}`);
                this.name = 'HttpError';
                this.response = response;
            }
        }
        function loadJson(url) {
            return fetch(url)
                .then(response => {
                    if (response.status == 200) {
                        return response.json();
                    } else {
                        throw new HttpError(response);
                    }
                })
        }
        // Запрашивать логин, пока github не вернёт существующего пользователя.
        function demoGithubUser() {
            let name = prompt("Введите логин?", "iliakan");
            return loadJson(`https://api.github.com/users/${name}`)
                .then(user => {
                    alert(`Полное имя: ${user.name}.`);
                    return user;
                })
                .catch(err => {
                    if (err instanceof HttpError && err.response.status == 404) {
                        alert("Такого пользователя не существует, пожалуйста, повторите ввод.");
                        return demoGithubUser();
                    } else {
                        throw err;
                    }
                });
        }
        demoGithubUser();

        // Ответ:

        class HttpError extends Error {
            constructor(response) {
                super(`${response.status} for ${response.url}`);
                this.name = 'HttpError';
                this.response = response;
            }
        }

        async function loadJson(url) {
            let response = await fetch(url);
            if (response.status == 200) {
                return response.json();
            } else {
                throw new HttpError(response);
            }
        }

        // Запрашивать логин, пока github не вернёт существующего пользователя.
        async function demoGithubUser() {

            let user;
            while (true) {
                let name = prompt("Введите логин?", "iliakan");

                try {
                    user = await loadJson(`https://api.github.com/users/${name}`);
                    break; // ошибок не было, выходим из цикла
                } catch (err) {
                    if (err instanceof HttpError && err.response.status == 404) {
                        // после alert начнётся новая итерация цикла
                        alert("Такого пользователя не существует, пожалуйста, повторите ввод.");
                    } else {
                        // неизвестная ошибка, пробрасываем её
                        throw err;
                    }
                }
            }
            alert(`Полное имя: ${user.name}.`);
            return user;
        }
        demoGithubUser();


        // №_3
        // Есть «обычная» функция. Как можно внутри неё получить результат выполнения async–функции?
        async function wait() {
            await new Promise(resolve => setTimeout(resolve, 1000));

            return 10;
        }

        function f() {
            // ...что здесь написать?
            // чтобы вызвать wait() и дождаться результата "10" от async–функции
            // не забывайте, здесь нельзя использовать "await"
        }

        // Ответ:

        async function wait() {
            await new Promise(resolve => setTimeout(resolve, 1000));

            return 10;
        }

        function f() {
            wait().then(result => alert(result));
        }
        f();
    </script>
</body>

</html>